### ISSUE TITLE
transfering ownership

### ISSUE THREAD

**Issue by leftieFriele** [micha149/gulp-maven-deploy#9]
I'll be transfering the ownership to you @micha149, please update the package.json information to make sure it reflects the new owner :)

**Comment by micha149** [comment]
@leftieFriele Can you update the npm owner list, please?!

**Comment by leftieFriele** [comment]
what's you npm username?

On Wed, Jun 3, 2015 at 9:04 AM, Michael van Engelshoven <
notifications@github.com> wrote:

> @leftieFriele <https://github.com/leftieFriele> Can you update the npm
> owner list, please?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/micha149/gulp-maven-deploy/issues/9#issuecomment-108220645>
> .
>



-- 
<quote goes here>
-----------------------------------------------------------------------
Espen Dalløkken

**Comment by micha149** [comment]
its `micha149`

**Comment by leftieFriele** [comment]
transfer complete, thanks for taking on this project!

On Wed, Jun 3, 2015 at 10:11 AM, Michael van Engelshoven <
notifications@github.com> wrote:

> its micha149
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/micha149/gulp-maven-deploy/issues/9#issuecomment-108239059>
> .
>



-- 
<quote goes here>
-----------------------------------------------------------------------
Espen Dalløkken
